### ISSUE TITLE
Resource Formatting

### ISSUE THREAD

**Issue by tskarhed** [bcarlyle/wellness#2]
Wonderful concept! 👍 

Just some general thoughts:
In what way should one provide resources? Are we talking about listing links or just writing plain text?

One source of inspiration could be [this repo for design resources](https://github.com/gztchan/awesome-design)

Let's discuss! :)

**Comment by BirgerMoell** [comment]
I think that page looks fantastic! Yes. I think it would be good to have it in a similar fashion. If the content is in a short format I think it could be good to have it inline and longer format information could be linked to.
